chore: use shell env-vars over .env.public file

diff --git a/bin/onesetup b/bin/onesetup
--- a/bin/onesetup
+++ b/bin/onesetup
@@ -3,22 +3,29 @@
 # --   ONESETUP EXECUTABLE   -- #
 # --                         -- #
 
-# -- Helper Functions -- #
+# -- Helper Script -- #
 function helper() {
-  # Load Helper Script
-  { source "$ONESETUP_DIR/scripts/helper.sh" && echo -e "${I_OK}Helper Script Loaded."; } || { echo -e "${I_ERR}Failed to load Helper Script. Please ensure your installation was correct." && exit 1; }
-  # Load Environment Variables
-  { set -a && source "$ONESETUP_DIR/.env.public" && set +a && echo -e "${I_OK}Environment Variables Loaded from '.env.public'."; } || { echo -e "${I_WARN}Failed to load Environment Variables from $ONESETUP_DIR/.env.public'."; }
+  source "$ONESETUP_DIR/scripts/helper.sh" || { echo -e "${I_ERR}Failed to load Helper Script. Please ensure your installation was correct." && exit 1; }
 }
 
 # -- Main Function -- #
 function main() {
-  echo "$TEST_VAR"
-  # Environment Variables
-  export ONESETUP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/onesetup"
-  export ONESETUP_REPO="onexbash/onesetup"
-  export DOTFILES_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles"
-  export DOTFILES_REPO="onexbash/dotfiles"
+  # Environment Variables (only set if unset)
+  if [[ -z "${ONESETUP_DIR:-}" ]]; then
+    export ONESETUP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/onesetup"
+  fi
+  if [[ -z "${ONESETUP_REPO:-}" ]]; then
+    export ONESETUP_REPO="onexbash/onesetup"
+  fi
+  if [[ -z "${DOTFILES_DIR:-}" ]]; then
+    export DOTFILES_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles"
+  fi
+  if [[ -z "${DOTFILES_REPO:-}" ]]; then
+    export DOTFILES_REPO="onexbash/dotfiles"
+  fi
+  if [[ -z "${ANSIBLE_DEBUG:-}" ]]; then
+    export ANSIBLE_DEBUG=0
+  fi
   # Variables
   VERSION="1.0.0"
   SCRIPT_NAME=$(basename "$0")
